const int OPTIMISATION = 1;
const int N_PROBLEMS = 50;
const int N_BLOCKS = 32;
const int GLOBAL_P = 10000;
const int GLOBAL_d = 300;
const int N_THREADS = 1000; // N_THREADS > 1 REQUIRED
const int GLOBAL_min_A = 0;
const int GLOBAL_max_A = 10;
const bool DEBUG = false;
const int NB_EXP = 15;